local c = require("theme.colors")

local function set_hl(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

local function apply()
    -- Base
    set_hl("Normal", { fg = c.fg })
    set_hl("NormalNC", { fg = c.fg })
    set_hl("NormalFloat", { fg = c.fg, bg = c.surface })
    set_hl("FloatBorder", { fg = c.border, bg = c.surface })
    set_hl("EndOfBuffer", { fg = c.muted })
    set_hl("SignColumn", {})
    set_hl("VertSplit", { fg = c.border })
    set_hl("WinSeparator", { fg = c.border })
    set_hl("NonText", { fg = c.muted })

    -- Line numbers
    set_hl("LineNr", { fg = c.muted })
    set_hl("CursorLineNr", { fg = c.accent })
    set_hl("CursorLine", { bg = c.surface })

    -- Syntax (standard groups)
    set_hl("Comment", { fg = c.muted, italic = true })
    set_hl("Constant", { fg = c.accent })
    set_hl("String", { fg = c.accent })
    set_hl("Character", { fg = c.accent })
    set_hl("Number", { fg = c.accent })
    set_hl("Boolean", { fg = c.accent })
    set_hl("Float", { fg = c.accent })
    set_hl("Identifier", { fg = c.fg })
    set_hl("Function", { fg = c.fg })
    set_hl("Statement", { fg = c.accent })
    set_hl("Conditional", { fg = c.accent })
    set_hl("Repeat", { fg = c.accent })
    set_hl("Label", { fg = c.accent })
    set_hl("Operator", { fg = c.border })
    set_hl("Keyword", { fg = c.accent })
    set_hl("Exception", { fg = c.danger })
    set_hl("PreProc", { fg = c.accent })
    set_hl("Include", { fg = c.accent })
    set_hl("Define", { fg = c.accent })
    set_hl("Macro", { fg = c.accent })
    set_hl("PreCondit", { fg = c.accent })
    set_hl("Type", { fg = c.accent })
    set_hl("StorageClass", { fg = c.accent })
    set_hl("Structure", { fg = c.accent })
    set_hl("Typedef", { fg = c.accent })
    set_hl("Special", { fg = c.border })
    set_hl("SpecialChar", { fg = c.border })
    set_hl("Tag", { fg = c.accent })
    set_hl("Delimiter", { fg = c.muted })
    set_hl("SpecialComment", { fg = c.accent_soft, italic = true })
    set_hl("Debug", { fg = c.danger })
    set_hl("Underlined", { fg = c.accent_soft, underline = true })
    set_hl("Error", { fg = c.danger })
    set_hl("Todo", { fg = c.bg, bg = c.accent, bold = true })

    -- Treesitter
    set_hl("@comment", { link = "Comment" })
    set_hl("@string", { fg = c.accent })
    set_hl("@string.escape", { fg = c.border })
    set_hl("@string.regex", { fg = c.border })
    set_hl("@string.special", { fg = c.border })
    set_hl("@character", { fg = c.accent })
    set_hl("@number", { fg = c.accent })
    set_hl("@boolean", { fg = c.accent })
    set_hl("@float", { fg = c.accent })
    set_hl("@function", { fg = c.fg })
    set_hl("@function.builtin", { fg = c.accent })
    set_hl("@function.call", { fg = c.fg })
    set_hl("@function.macro", { fg = c.accent })
    set_hl("@method", { fg = c.fg })
    set_hl("@method.call", { fg = c.fg })
    set_hl("@constructor", { fg = c.accent })
    set_hl("@parameter", { fg = c.fg })
    set_hl("@keyword", { fg = c.accent })
    set_hl("@keyword.function", { fg = c.accent })
    set_hl("@keyword.operator", { fg = c.accent })
    set_hl("@keyword.return", { fg = c.accent })
    set_hl("@conditional", { fg = c.accent })
    set_hl("@repeat", { fg = c.accent })
    set_hl("@label", { fg = c.accent })
    set_hl("@operator", { fg = c.border })
    set_hl("@exception", { fg = c.danger })
    set_hl("@variable", { fg = c.fg })
    set_hl("@variable.builtin", { fg = c.accent })
    set_hl("@type", { fg = c.accent })
    set_hl("@type.builtin", { fg = c.accent })
    set_hl("@type.definition", { fg = c.accent })
    set_hl("@type.qualifier", { fg = c.accent })
    set_hl("@storageclass", { fg = c.accent })
    set_hl("@namespace", { fg = c.fg })
    set_hl("@include", { fg = c.accent })
    set_hl("@preproc", { fg = c.accent })
    set_hl("@define", { fg = c.accent })
    set_hl("@constant", { fg = c.accent })
    set_hl("@constant.builtin", { fg = c.accent })
    set_hl("@constant.macro", { fg = c.accent })
    set_hl("@property", { fg = c.fg })
    set_hl("@field", { fg = c.fg })
    set_hl("@attribute", { fg = c.accent })
    set_hl("@punctuation.delimiter", { fg = c.muted })
    set_hl("@punctuation.bracket", { fg = c.muted })
    set_hl("@punctuation.special", { fg = c.border })
    set_hl("@tag", { fg = c.accent })
    set_hl("@tag.attribute", { fg = c.accent_soft })
    set_hl("@tag.delimiter", { fg = c.muted })
    set_hl("@text", { fg = c.fg })
    set_hl("@text.strong", { fg = c.fg, bold = true })
    set_hl("@text.emphasis", { fg = c.fg, italic = true })
    set_hl("@text.underline", { fg = c.fg, underline = true })
    set_hl("@text.strike", { fg = c.muted, strikethrough = true })
    set_hl("@text.title", { fg = c.accent, bold = true })
    set_hl("@text.literal", { fg = c.accent })
    set_hl("@text.uri", { fg = c.accent, underline = true })
    set_hl("@text.todo", { fg = c.bg, bg = c.accent, bold = true })
    set_hl("@text.note", { fg = c.bg, bg = c.accent })
    set_hl("@text.warning", { fg = c.bg, bg = c.danger_soft })
    set_hl("@text.danger", { fg = c.bg, bg = c.danger })

    -- LSP diagnostics
    set_hl("DiagnosticError", { fg = c.danger })
    set_hl("DiagnosticWarn", { fg = c.accent })
    set_hl("DiagnosticInfo", { fg = c.accent })
    set_hl("DiagnosticHint", { fg = c.muted })

    -- Telescope
    set_hl("TelescopeBorder", { fg = c.border })
    set_hl("TelescopeNormal", { bg = c.surface })
    set_hl("TelescopeSelection", { fg = c.fg, bg = c.surface })
    set_hl("TelescopeMatching", { fg = c.accent, bold = true })
    set_hl("TelescopePromptPrefix", { fg = c.accent })
    set_hl("TelescopeResultsClass", { fg = c.fg })
    set_hl("TelescopeResultsConstant", { fg = c.fg })
    set_hl("TelescopeResultsField", { fg = c.fg })
    set_hl("TelescopeResultsFunction", { fg = c.fg })
    set_hl("TelescopeResultsMethod", { fg = c.fg })
    set_hl("TelescopeResultsProperty", { fg = c.fg })
    set_hl("TelescopeResultsVariable", { fg = c.fg })
    set_hl("TelescopeResultsNumber", { fg = c.fg })
    set_hl("TelescopeResultsLineNr", { fg = c.fg })
    set_hl("TelescopeResultsIdentifier", { fg = c.fg })

    -- NvimTree
    set_hl("Directory", { fg = c.accent })
    set_hl("NvimTreeNormal", {})
    set_hl("NvimTreeFolderIcon", { fg = c.accent })
    set_hl("NvimTreeOpenedFolderName", { fg = c.accent, bold = true })
    set_hl("NvimTreeFolderName", { fg = c.accent })
    set_hl("NvimTreeFileName", { fg = c.fg })
    set_hl("NvimTreeRootFolder", { fg = c.accent, bold = true })
    set_hl("NvimTreeEmptyFolderName", { fg = c.muted })
    set_hl("NvimTreeOpenedFile", { fg = c.fg })
    set_hl("NvimTreeExecFile", { fg = c.fg })
    set_hl("NvimTreeSpecialFile", { fg = c.accent })
    set_hl("NvimTreeSymlink", { fg = c.accent })
    set_hl("NvimTreeIndentMarker", { fg = c.border })
    set_hl("NvimTreeGitDirty", { fg = c.accent })
    set_hl("NvimTreeGitStaged", { fg = c.accent })
    set_hl("NvimTreeGitMerge", { fg = c.danger })
    set_hl("NvimTreeGitRenamed", { fg = c.accent })
    set_hl("NvimTreeGitNew", { fg = c.accent })
    set_hl("NvimTreeGitDeleted", { fg = c.danger })

    -- Status line
    set_hl("StatusLine", { fg = c.fg, bg = c.surface })
    set_hl("StatusLineNC", { fg = c.muted, bg = c.surface })

    -- Messages
    set_hl("ErrorMsg", { fg = c.danger })
    set_hl("WarningMsg", { fg = c.accent })
    set_hl("InfoMsg", { fg = c.accent })
    set_hl("ModeMsg", { fg = c.accent })
    set_hl("MoreMsg", { fg = c.accent })
    set_hl("Question", { fg = c.accent })

    -- Completion menu
    set_hl("Pmenu", { fg = c.fg, bg = c.surface })
    set_hl("PmenuSel", { fg = c.bg, bg = c.accent })
    set_hl("PmenuSbar", { bg = c.muted })
    set_hl("PmenuThumb", { bg = c.border })
end

local function setup()
    -- Apply immediately
    apply()

    -- Re-apply after colorscheme changes (plugins might set one)
    vim.api.nvim_create_autocmd("ColorScheme", {
        group = vim.api.nvim_create_augroup("custom-theme", { clear = true }),
        callback = apply,
    })

    -- Re-apply on VimEnter to ensure it's set after all plugins
    vim.api.nvim_create_autocmd("VimEnter", {
        callback = apply,
    })
end

return { setup = setup, colors = c }
