# Generated via themegen/render.py from palette.toml

[colors.primary]
background = "#e6e2e1"
foreground = "#3b3936"

[colors.cursor]
text = "#3b3936"
cursor = "#596369"

[colors.selection]
text = "#3b3936"
background = "#8d8c84"

[colors.normal]
black   = "#e6e2e1"
red     = "#596369"
green   = "#8d8c84"
yellow  = "#83909a"
blue    = "#8d8c84"
magenta = "#596369"
cyan    = "#83909a"
white   = "#3b3936"

[colors.bright]
black   = "#4b4f4d"
red     = "#596369"
green   = "#8d8c84"
yellow  = "#83909a"
blue    = "#8d8c84"
magenta = "#596369"
cyan    = "#83909a"
white   = "#3b3936"
