# Generated via themegen/render.py from palette.toml

[colors.primary]
background = "#e6e2e1"
foreground = "#5a5751"

[colors.cursor]
text = "#fdf7e3"
cursor = "#1e1c1a"

[colors.selection]
text = "#5a5751"
background = "#d7c7b5"

[colors.normal]
black   = "#e6e2e1"
red     = "#adb5c2"
green   = "#a2a39d"
yellow  = "#ced2db"
blue    = "#adb5c2"
magenta = "#adb5c2"
cyan    = "#ced2db"
white   = "#5a5751"

[colors.bright]
black   = "#a2a39d"
red     = "#adb5c2"
green   = "#a2a39d"
yellow  = "#ced2db"
blue    = "#adb5c2"
magenta = "#adb5c2"
cyan    = "#ced2db"
white   = "#5a5751"
