# Generated via themegen/render.py from palette.toml

[colors.primary]
background = "#e6e2e1"
foreground = "#3b3936"

[colors.cursor]
text = "#f3efe6"
cursor = "#1e1c1a"

[colors.selection]
text = "#3b3936"
background = "#8b765c"

[colors.normal]
black   = "#e6e2e1"
red     = "#596369"
green   = "#6f6f6c"
yellow  = "#83909a"
blue    = "#7f878b"
magenta = "#596369"
cyan    = "#879197"
white   = "#3b3936"

[colors.bright]
black   = "#4b4f4d"
red     = "#596369"
green   = "#6f6f6c"
yellow  = "#83909a"
blue    = "#7f878b"
magenta = "#596369"
cyan    = "#879197"
white   = "#3b3936"
